version: '3.5'

services:
  webserver:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    container_name: webserver_test
    volumes:
      - ./:/var/www
      # - ./.docker/nginx/sites:/etc/nginx/conf.d
      - ./.docker/nginx/sites:/etc/nginx/conf.d
      - ./storage/logs/nginx:/var/log/nginx
    ports:
      - 80:80
    links:
      - app

  app:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: app_test
    volumes:
      - ./:/var/www
      - ./.docker/php/config/general.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - mysql
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_test
    volumes:
      - ./storage/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=bloodbank
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_test
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - mysql

  cli:
    build:
      context: ./.docker/cli
    container_name: cli_test
    volumes:
      - ./:/var/www
    tty: true
    links:
      - mysql